language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install -r requirements.txt
  - python setup.py install

before_script: wget https://www.kaggle.com/c/titanic/download/train.csv -P data/

script: pytest