language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

before_install:
  - pip install --upgrade pip setuptools wheel

install:
  - pip install --only-binary=numpy,scipy -r requirements.txt
  - python setup.py install

before_script: wget https://www.kaggle.com/c/titanic/download/train.csv -P data/

script: pytest